FROM node:22-alpine AS deps

WORKDIR /app

COPY package.json ./
RUN npm install


FROM deps AS dev

CMD ["npm", "run", "dev"]


FROM deps AS builder

COPY . .
RUN npm run build


FROM nginx:alpine AS production

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
