name: Security Checks

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

jobs:
  security-checks:
    if: (github.actor != 'dependabot[bot]')
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          hide-progress: false
          scan-ref: .
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/default
